return {
  {
    "m4xshen/hardtime.nvim",
    dependencies = { "MunifTanjim/nui.nvim", "nvim-lua/plenary.nvim" },
    opts = {
      disabled_filetypes = {
        "NvimTree",
        "aerial",
        "alpha",
        "dap-repl",
        "dapui_breakpoints",
        "dapui_console",
        "dapui_scopes",
        "dapui_stacks",
        "dapui_watches",
        "dbout",
        "dbui",
        "help",
        "lazy",
        "mason",
        "neo-tree",
        "neo-tree-popup",
        "netrw",
        "noice",
        "octo",
        "oil",
        "overseerlist",
        "qf",
        "toggleterm",
      },
    },
    event = "BufEnter",
  },
}
