return {
  auto_update = true,
  ensure_installed = {
    "sumneko_lua",
    "rust_analyzer",
    "clangd",
    "intelephense",
    "tailwindcss",
    "yaml-language-server",
    "vue-language-server",
    "typescript-language-server",
    "pyright",
    "marksman",
    "nimlsp",
    "mypy",
    "eslint-lsp",
    "css-lsp",
    "sqll",
  },
}
