return {
  { "nyoom-engineering/oxocarbon.nvim" },
  -- {
  --   "uloco/bluloco.nvim",
  --   lazy = false,
  --   priority = 1500,
  --   dependencies = { "rktjmp/lush.nvim" },
  --   config = function()
  --     require("bluloco").setup {
  --       style = "auto",
  --       transparent = false,
  --       italics = true,
  --       terminal = true,
  --       guicursor = true,
  --     }
  --   end,
  -- },
  -- { 'frenzyexists/aquarium-vim' },
  -- {
  --   "rose-pine/neovim",
  --   as = "rose-pine",
  --   config = function() require("rose-pine").setup { dark_variant = "moon" } end,
  -- },
  -- { "arcticicestudio/nord-vim" },
  -- { 'sainnhe/edge' },
  -- { "shaunsingh/solarized.nvim" },
  -- { "sainnhe/sonokai" },
  -- { "Yazeed1s/oh-lucy.nvim" },
  -- {
  --   "catppuccin/nvim",
  --   as = "catppuccin",
  --   config = function()
  --     require("catppuccin").setup {
  --       dim_inactive = {
  --         enabled = false,
  --         shade = "dark",
  --         percentage = 0.15,
  --       },
  --     }
  --   end,
  -- },
  -- { "EdenEast/nightfox.nvim", run = ":NightfoxCompile" },
  -- { 'sainnhe/everforest' },
  -- { "folke/tokyonight.nvim" },
  -- { "navarasu/onedark.nvim" },
  -- { 'KeitaNakamura/neodark.vim' },
}
